name: orchidCD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ordid-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
   # - name: Copy .env
    #  run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: clear cache
      run: composer clear-cache
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Clear Optimized Classes
      run: php artisan optimize:clear
    - name: Run Migrations
      run: php artisan migrate --force
    - name: Seed Database
      run: php artisan db:seed --force
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        server-dir: /public_html/orchidapi01/
        exclude: |
          **/.git**
          **/.git*/**
          **/node_modules/**
          **/.**
        if: success()  # This step will only run if the previous steps were successful
